import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { resolveAgentWorkspaceDir } from "../agents/agent-scope.js";
import { loadWorkspaceSkillEntries } from "../agents/skills.js";
import { loadConfig } from "../config/config.js";
import { info, success, danger } from "../globals.js";
import {
  aggregateAccessPolicy,
  CHANNEL_DOMAINS,
  PROVIDER_DOMAINS,
  type AccessManifestSource,
} from "../infra/access-manifest.js";
import { loadPluginManifest } from "../plugins/manifest.js";

type GeneratePolicyOptions = {
  output?: string;
  save?: boolean;
  audit?: boolean;
  includeUndeclared?: boolean;
  applyRules?: boolean;
  agent?: string;
};

export async function greywallGeneratePolicy(opts: GeneratePolicyOptions) {
  const cfg = await loadConfig();

  // Collect access sources from skills
  const sources: AccessManifestSource[] = [];

  // Gather skill access manifests
  try {
    const workspaceDir = opts.agent ? resolveAgentWorkspaceDir(cfg, opts.agent) : process.cwd();
    const skills = loadWorkspaceSkillEntries(workspaceDir, { config: cfg });
    for (const entry of skills) {
      sources.push({
        id: entry.skill.name,
        kind: "skill",
        access: entry.metadata?.access,
      });
    }
  } catch {
    // Skills may not be loadable in all contexts
  }

  // Gather plugin access manifests from extensions directory
  try {
    const extensionsDir = path.resolve("extensions");
    if (fs.existsSync(extensionsDir)) {
      const entries = fs.readdirSync(extensionsDir, { withFileTypes: true });
      for (const entry of entries) {
        if (!entry.isDirectory()) continue;
        const manifestPath = path.join(extensionsDir, entry.name, "openclaw.plugin.json");
        if (!fs.existsSync(manifestPath)) continue;
        const result = await loadPluginManifest(manifestPath);
        if (result.ok) {
          sources.push({
            id: result.manifest.id,
            kind: "plugin",
            access: result.manifest.access,
          });
        }
      }
    }
  } catch {
    // Plugin loading may fail
  }

  // Detect configured channels from config
  const configuredChannels: string[] = [];
  const channelsSection = (cfg as Record<string, unknown>).channels;
  if (channelsSection && typeof channelsSection === "object") {
    for (const key of Object.keys(channelsSection as Record<string, unknown>)) {
      if (key in CHANNEL_DOMAINS) {
        configuredChannels.push(key);
      }
    }
  }

  // Detect provider from agent model config
  const configuredProviders: string[] = [];
  const agentsSection = (cfg as Record<string, unknown>).agents;
  if (agentsSection && typeof agentsSection === "object") {
    const defaults = (agentsSection as Record<string, unknown>).defaults;
    if (defaults && typeof defaults === "object") {
      const model = (defaults as Record<string, unknown>).model;
      if (model && typeof model === "object") {
        const primary = (model as Record<string, unknown>).primary;
        if (typeof primary === "string") {
          const providerPrefix = primary.split("/")[0];
          if (providerPrefix && providerPrefix in PROVIDER_DOMAINS) {
            configuredProviders.push(providerPrefix);
          }
        }
      }
    }
  }
  // Always include anthropic as default provider
  if (!configuredProviders.includes("anthropic")) {
    configuredProviders.push("anthropic");
  }

  const policy = aggregateAccessPolicy(sources, {
    channels: configuredChannels,
    providers: configuredProviders,
  });

  // Audit mode
  if (opts.audit) {
    printAudit(sources, policy, configuredChannels, configuredProviders);
    return;
  }

  // Build greywall.json policy
  const greywallConfig = {
    _comment: "Generated by: openclaw greywall generate-policy",
    _sources: `${sources.length} sources (${policy.undeclared.length} undeclared)`,
    _channels: configuredChannels.length > 0 ? configuredChannels.join(", ") : "none detected",
    extends: "code",
    network: {
      proxyUrl: "socks5://localhost:43052",
      dnsAddr: "localhost:43053",
    },
    filesystem: {
      defaultDenyRead: true,
      allowRead: policy.read,
      allowWrite: policy.write,
      denyRead: policy.denyRead,
      denyWrite: policy.denyWrite,
    },
    command: {
      useDefaults: true,
    },
  };

  const json = JSON.stringify(greywallConfig, null, 2);

  if (opts.save) {
    const outPath = path.resolve("greywall.json");
    fs.writeFileSync(outPath, json + "\n");
    success(`Policy written to ${outPath}`);
  } else if (opts.output) {
    fs.writeFileSync(opts.output, json + "\n");
    success(`Policy written to ${opts.output}`);
  } else {
    console.log(json);
  }

  // Log domain summary
  if (policy.domains.length > 0) {
    info(`Policy includes ${policy.domains.length} allowed domain(s)`);
  }

  // Apply domain rules to GreyProxy
  if (opts.applyRules && policy.domains.length > 0) {
    try {
      const rules = policy.domains.map((domain) => {
        const source = sources.find((s) => s.access?.domains?.includes(domain));
        return {
          destination_pattern: domain,
          container_pattern: "*",
          action: "allow",
          created_by: "openclaw-policy",
          notes: source ? `${source.kind}:${source.id}` : undefined,
        };
      });

      const res = await fetch("http://localhost:43080/api/rules/ingest", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(rules),
        signal: AbortSignal.timeout(10_000),
      });

      if (res.ok) {
        success(`Ingested ${rules.length} domain rule(s) into GreyProxy`);
      } else {
        danger(`GreyProxy rules ingest failed: ${res.status} ${res.statusText}`);
      }
    } catch (err) {
      danger(`GreyProxy not reachable: ${err instanceof Error ? err.message : String(err)}`);
    }
  }
}

function printAudit(
  sources: AccessManifestSource[],
  policy: ReturnType<typeof aggregateAccessPolicy>,
  channels: string[],
  providers: string[],
) {
  console.log("\n📋 Access Policy Audit\n");

  if (channels.length > 0) {
    console.log(`Channels detected: ${channels.join(", ")}`);
  }
  if (providers.length > 0) {
    console.log(`Providers detected: ${providers.join(", ")}`);
  }
  console.log();

  const skills = sources.filter((s) => s.kind === "skill");
  const plugins = sources.filter((s) => s.kind === "plugin");

  const hasAccess = (s: AccessManifestSource) =>
    s.access !== undefined &&
    ((s.access.domains?.length ?? 0) > 0 ||
      (s.access.read?.length ?? 0) > 0 ||
      (s.access.write?.length ?? 0) > 0);
  const optedOut = (s: AccessManifestSource) => s.access !== undefined && !hasAccess(s);

  const skillsWithAccess = skills.filter(hasAccess).length;
  const skillsOptedOut = skills.filter(optedOut).length;
  const skillsUndeclared = skills.length - skillsWithAccess - skillsOptedOut;
  const pluginsWithAccess = plugins.filter(hasAccess).length;
  const pluginsOptedOut = plugins.filter(optedOut).length;
  const pluginsUndeclared = plugins.length - pluginsWithAccess - pluginsOptedOut;

  if (skills.length > 0) {
    const parts = [`${skillsWithAccess} with manifests`];
    if (skillsOptedOut > 0) parts.push(`${skillsOptedOut} no-access`);
    if (skillsUndeclared > 0) parts.push(`${skillsUndeclared} undeclared`);
    console.log(`Skills (${skills.length} active, ${parts.join(", ")}):`);
    for (const s of skills) {
      if (hasAccess(s)) {
        const parts: string[] = [];
        if (s.access!.domains?.length) parts.push(s.access!.domains.join(", "));
        if (s.access!.read?.length) parts.push(`read: ${s.access!.read.join(", ")}`);
        if (s.access!.write?.length) parts.push(`write: ${s.access!.write.join(", ")}`);
        console.log(`  ✅ ${s.id.padEnd(20)} → ${parts.join(" | ")}`);
      } else if (optedOut(s)) {
        console.log(`  ✅ ${s.id.padEnd(20)} → no access needed`);
      } else {
        console.log(`  ⚠️  ${s.id.padEnd(20)} → no access manifest declared`);
      }
    }
    console.log();
  }

  if (plugins.length > 0) {
    const parts = [`${pluginsWithAccess} with manifests`];
    if (pluginsOptedOut > 0) parts.push(`${pluginsOptedOut} no-access`);
    if (pluginsUndeclared > 0) parts.push(`${pluginsUndeclared} undeclared`);
    console.log(`Plugins (${plugins.length} active, ${parts.join(", ")}):`);
    for (const s of plugins) {
      if (hasAccess(s)) {
        const parts: string[] = [];
        if (s.access!.domains?.length) parts.push(s.access!.domains.join(", "));
        if (s.access!.read?.length) parts.push(`read: ${s.access!.read.join(", ")}`);
        if (s.access!.write?.length) parts.push(`write: ${s.access!.write.join(", ")}`);
        console.log(`  ✅ ${s.id.padEnd(20)} → ${parts.join(" | ")}`);
      } else if (optedOut(s)) {
        console.log(`  ✅ ${s.id.padEnd(20)} → no access needed`);
      } else {
        console.log(`  ⚠️  ${s.id.padEnd(20)} → no access manifest declared`);
      }
    }
    console.log();
  }

  console.log("Aggregated Policy:");
  console.log(`  Domains: ${policy.domains.length} unique`);
  console.log(`  Read paths: ${policy.read.length}`);
  console.log(`  Write paths: ${policy.write.length}`);
  console.log(`  Deny read: ${policy.denyRead.length} (hardcoded)`);
  console.log(`  Deny write: ${policy.denyWrite.length} (hardcoded)`);
  console.log();
}

// ── greywall start ──────────────────────────────────────────────────

type GreywallStartOptions = {
  profile?: string;
  gatewayArgs?: string[];
};

/**
 * Seed GreyProxy domain rules then exec `greywall -- openclaw gateway`.
 * Runs outside the sandbox so localhost:43080 is reachable.
 */
export async function greywallStart(opts: GreywallStartOptions) {
  const cfg = await loadConfig();

  // Detect channels and providers from config (same logic as generate-policy)
  const configuredChannels: string[] = [];
  const channelsSection = (cfg as Record<string, unknown>).channels;
  if (channelsSection && typeof channelsSection === "object") {
    for (const key of Object.keys(channelsSection as Record<string, unknown>)) {
      if (key in CHANNEL_DOMAINS) {
        configuredChannels.push(key);
      }
    }
  }

  const configuredProviders: string[] = [];
  const agentsSection = (cfg as Record<string, unknown>).agents;
  if (agentsSection && typeof agentsSection === "object") {
    const defaults = (agentsSection as Record<string, unknown>).defaults;
    if (defaults && typeof defaults === "object") {
      const model = (defaults as Record<string, unknown>).model;
      if (model && typeof model === "object") {
        const primary = (model as Record<string, unknown>).primary;
        if (typeof primary === "string") {
          const providerPrefix = primary.split("/")[0];
          if (providerPrefix && providerPrefix in PROVIDER_DOMAINS) {
            configuredProviders.push(providerPrefix);
          }
        }
      }
    }
  }
  if (!configuredProviders.includes("anthropic")) {
    configuredProviders.push("anthropic");
  }

  // Build domain list from base + channels + providers + skill/plugin manifests
  const sources: AccessManifestSource[] = [];
  try {
    const workspaceDir = process.cwd();
    const skills = loadWorkspaceSkillEntries(workspaceDir, { config: cfg });
    for (const entry of skills) {
      sources.push({
        id: entry.skill.name,
        kind: "skill",
        access: entry.metadata?.access,
      });
    }
  } catch {
    // Skills may not be loadable in all contexts
  }

  const policy = aggregateAccessPolicy(sources, {
    channels: configuredChannels,
    providers: configuredProviders,
  });

  // Seed rules into GreyProxy (runs outside the sandbox, localhost:43080 is reachable)
  if (policy.domains.length > 0) {
    try {
      const rules = policy.domains.map((domain) => ({
        destination_pattern: domain,
        container_pattern: "*",
        action: "allow",
        created_by: "openclaw-gateway",
        notes: configuredChannels.includes(domain) ? `channel` : undefined,
      }));

      const res = await fetch("http://localhost:43080/api/rules/ingest", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(rules),
        signal: AbortSignal.timeout(10_000),
      });

      if (res.ok) {
        success(`Seeded ${rules.length} domain rule(s) into GreyProxy`);
      } else {
        danger(`GreyProxy rules ingest failed: ${res.status} ${res.statusText}`);
      }
    } catch (err) {
      danger(
        `GreyProxy not reachable at localhost:43080: ${err instanceof Error ? err.message : String(err)}`,
      );
      danger("Start GreyProxy first: greywall setup");
      process.exit(1);
    }
  }

  // Build greywall command
  const profile = opts.profile ?? "openclaw";
  const gatewayArgs = opts.gatewayArgs ?? [];
  const entrypoint = process.argv[1] ?? "./openclaw.mjs";
  const args = ["--profile", profile, "--", entrypoint, "gateway", ...gatewayArgs];

  info(`Starting gateway behind greywall (profile: ${profile})`);

  // Greywall env vars for the sandboxed gateway process:
  //
  // ALL_PROXY: The SOCKS5 proxy URL so that code inside the sandbox can detect
  //   and route through it. Seatbelt blocks ALL direct outbound TCP — only
  //   connections to the SOCKS5 proxy port are permitted. Without this env var,
  //   internal WebSocket self-connections (cron, agents) fail with 1006.
  //
  // NO_PROXY: Loopback bypass for undici/fetch HTTP requests (GreyProxy API,
  //   browser control, etc.) so they don't try to SOCKS-tunnel simple HTTP calls
  //   that the proxy itself serves.
  const greywallJsonPath = path.resolve("greywall.json");
  let socksProxyUrl = "socks5://localhost:43052"; // sensible default
  try {
    const greywallJson = JSON.parse(fs.readFileSync(greywallJsonPath, "utf8"));
    if (typeof greywallJson?.network?.proxyUrl === "string") {
      socksProxyUrl = greywallJson.network.proxyUrl;
    }
  } catch {
    // greywall.json may not exist; use default proxy URL
  }

  const loopbackEntries = "localhost,127.0.0.1,[::1]";
  const currentNoProxy = process.env.NO_PROXY || process.env.no_proxy || "";
  const noProxy =
    currentNoProxy.includes("localhost") && currentNoProxy.includes("127.0.0.1")
      ? currentNoProxy
      : currentNoProxy
        ? `${currentNoProxy},${loopbackEntries}`
        : loopbackEntries;

  try {
    execFileSync("greywall", args, {
      stdio: "inherit",
      env: {
        ...process.env,
        ALL_PROXY: socksProxyUrl,
        NO_PROXY: noProxy,
        no_proxy: noProxy,
      },
    });
  } catch (err) {
    // execFileSync throws on non-zero exit; the child's stderr was already printed
    const code = (err as { status?: number }).status ?? 1;
    process.exit(code);
  }
}
